# Generated by Django 5.1.2 on 2024-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
