# Generated by Django 5.1.2 on 2024-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_material_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="imagem",
            field=models.ImageField(null=True, upload_to="material/"),
        ),
    ]
