# Generated by Django 5.1.2 on 2024-10-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_material_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="material/"),
        ),
    ]
