# Generated by Django 5.1.2 on 2024-10-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_material_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriavideos",
            name="descricao",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="categoriavideos",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="descricao/"),
        ),
    ]
