# Generated by Django 5.1.2 on 2024-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card_ferramentas",
            name="imagem",
            field=models.ImageField(upload_to="material/"),
        ),
    ]
