# Generated by Django 5.1.2 on 2024-10-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_card_ferramentas_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card_ferramentas",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="card_ferramentas",
            name="imagem",
            field=models.ImageField(upload_to="material/"),
        ),
    ]
